### ISSUE TITLE
datetime parse error

### ISSUE THREAD

**Issue by sayan801** [sayan801/pyccda#3]
````
chandra@chandraLapi:~/code/pyccda/pyccda$ python ccda_test.py 
E
======================================================================
ERROR: test_sample_ccda_files (__main__.CcdaDocumentTestCase)
Test all sample CCDA files in the testdata directory.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ccda_test.py", line 30, in test_sample_ccda_files
    self._test_to_csv(fp)
  File "ccda_test.py", line 15, in _test_to_csv
    ccda_csv = ccda_doc.to_csv()
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 185, in to_csv
    message = self.to_message()
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 302, in to_message
    date_node = entry.getElementsByTagName('effectiveTime')[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.623s

FAILED (errors=1)

````

- allscripts.xml - https://github.com/sayan801/pyccda/blob/master/testdata/allscripts.xml
- vitera~.xml - https://github.com/sayan801/pyccda/blob/master/testdata/Vitera_CCDA_SMART_Sample.xml

**Comment by sayan801** [comment]
````
chandra@chandraLapi:~/code/pyccda$ python technicise.py 
Traceback (most recent call last):
  File "technicise.py", line 13, in <module>
    ccda_message = ccda.to_message()
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 238, in to_message
    immunization.date = CcdaTree.get_date_from_effective_time(entry)
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 140, in get_date_from_effective_time
    return cls.get_date_from_value(val)
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 151, in get_date_from_value
    return datetime.datetime.strptime(val, datetime_format)
UnboundLocalError: local variable 'datetime_format' referenced before assignment
chandra@chandraLapi:~/code/pyccda$
````

**Comment by sayan801** [comment]
````
chandra@chandraLapi:~/code/pyccda$ python technicise.py 
Traceback (most recent call last):
  File "technicise.py", line 13, in <module>
    ccda_message = ccda.to_message()
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 307, in to_message
    date_node = entry.getElementsByTagName('effectiveTime')[0]
IndexError: list index out of range
````

**Comment by sayan801** [comment]
we need to change the way pyccda parses the effectiveTime... Here is a snippet from its parent js class

````
var date = parseDate(entry.tag('effectiveTime').attr('value'));
 if (!date) {
      date = parseDate(entry.tag('effectiveTime').tag('low').attr('value'));
 }
````

**Comment by sayan801** [comment]
# procedure sometimes returning effectiveTime as date range
````
 <entry typeCode="DRIV">
            <procedure classCode="PROC" moodCode="EVN">
              <templateId root="2.16.840.1.113883.10.20.22.4.14" assigningAuthorityName="CCDA Procedure Activity Procedure" />
              <id root="2.16.840.1.113883.3.140.1.0.6.10.17.2" extension="94" />
              <code code="85014" displayName="Hematocrit" codeSystem="2.16.840.1.113883.6.12" codeSystemName="CPT-4">
                <originalText>
                  <reference value="#procedureDescriptionID0" />
                </originalText>
              </code>
              <text>
                <reference value="#procedureDescriptionID0" />
              </text>
              <statusCode code="completed" />
              <effectiveTime>
                <low value="20070903" />
              </effectiveTime>
              <performer typeCode="PRF">
                <assignedEntity classCode="ASSIGNED">
                  <id root="2.16.840.1.113883.4.6" extension="9080089000" assigningAuthorityName="NPI" />
                  <addr>
                    <streetAddressLine>11554 Weedside Lane</streetAddressLine>
                    <city>Madison</city>
                    <state>CA</state>
                    <country>US</country>
                    <postalCode>95653</postalCode>
                  </addr>
                  <telecom value="tel:+1-916-555-7657" use="WP" />
                  <assignedPerson>
                    <name>
                      <given>James</given>
                      <given>T</given>
                      <family>Monroe</family>
                      <suffix>MD</suffix>
                    </name>
                  </assignedPerson>
                  <representedOrganization>
                    <id root="2.16.840.1.113883.3.140.1.0.6" extension="MMC" />
                    <name>Madison Medical Center P. A.</name>
                    <telecom value="tel:+1-916-555-7654" use="WP" />
                    <addr>
                      <streetAddressLine>99 Sycamore Street</streetAddressLine>
                      <streetAddressLine>Suite 3</streetAddressLine>
                      <city>Gainesville</city>
                      <state>FL</state>
                      <country>US</country>
                      <postalCode>32608</postalCode>
                    </addr>
                  </representedOrganization>
                </assignedEntity>
              </performer>
              <informant>
                <assignedEntity>
                  <id root="1e766183-7148-455c-89b6-113f2ecd2ccc" />
                  <addr>
                    <streetAddressLine>99 Sycamore Street</streetAddressLine>
                    <streetAddressLine>Suite 3</streetAddressLine>
                    <city>Gainesville</city>
                    <state>FL</state>
                    <country>US</country>
                    <postalCode>32608</postalCode>
                  </addr>
                  <telecom value="tel:+1-916-555-7654" use="WP" />
                  <assignedPerson>
                    <name nullFlavor="UNK" />
                  </assignedPerson>
                  <representedOrganization>
                    <id root="2.16.840.1.113883.3.140.1.0.6" extension="MMC" />
                    <name>Madison Medical Center P. A.</name>
                    <telecom value="tel:+1-916-555-7654" use="WP" />
                    <telecom value="tel:+1-916-555-7657" use="WP" />
                    <addr>
                      <streetAddressLine>99 Sycamore Street</streetAddressLine>
                      <streetAddressLine>Suite 3</streetAddressLine>
                      <city>Gainesville</city>
                      <state>FL</state>
                      <country>US</country>
                      <postalCode>32608</postalCode>
                    </addr>
                  </representedOrganization>
                </assignedEntity>
              </informant>
              <participant typeCode="LOC">
                <templateId root="2.16.840.1.113883.10.20.22.4.32" assigningAuthorityName="CCDA Encounter Location" />
                <participantRole classCode="SDLOC">
                  <id root="2.16.840.1.113883.3.140.1.0.6.5" extension="45" />
                  <code code="PROFF" displayName="Provider's Office" />
                  <addr>
                    <streetAddressLine>34 Sycamore Street, Suite 3</streetAddressLine>
                    <city>Gainesville</city>
                    <state>FL</state>
                    <country>US</country>
                    <postalCode>32608</postalCode>
                  </addr>
                  <telecom value="tel:+1-916-555-7654" use="WP" />
                  <playingEntity classCode="PLC">
                    <name>Office - Madison Medical Center, P.A.</name>
                  </playingEntity>
                </participantRole>
              </participant>
              <entryRelationship typeCode="SUBJ" inversionInd="false">
                <observation classCode="OBS" moodCode="EVN" negationInd="false">
                  <templateId root="2.16.840.1.113883.10.20.22.4.4" assigningAuthorityName="CCDA Problem Observation" />
                  <id root="42b34e97-d643-4801-bc4f-4c4bce9795e9" />
                  <code code="282291009" displayName="Diagnosis" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT" />
                  <text>
                    <reference value="#procedureDescription0" />
                  </text>
                  <statusCode code="completed" />
                  <effectiveTime>
                    <low value="20070903" />
                  </effectiveTime>
                  <value code="V70.0" displayName="ROUTINE GENERAL MEDICAL EXAM" codeSystem="2.16.840.1.113883.6.103" codeSystemName="ICD9CM" xsi:type="CD">
                    <originalText>
                      <reference value="#procedureDescription0" />
                    </originalText>
                  </value>
                </observation>
              </entryRelationship>
            </procedure>
          </entry>
````

**Comment by sayan801** [comment]
https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime

**Comment by sayan801** [comment]
````
chandra@chandraLapi:~/code/pyccda$ python technicise.py >dao5.json
Traceback (most recent call last):
  File "technicise.py", line 18, in <module>
    ccda_message = ccda.to_message()
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 419, in to_message
    vital.date = CcdaTree.get_date_from_effective_time(entry)
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 158, in get_date_from_effective_time
    returnVal =  cls.get_date_from_value(val)
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 177, in get_date_from_value
    return datetime.datetime.strptime(val, datetime_format)
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '20160307203700+0000' does not match format '%Y%m%d%H%M%S-%f'
````
