### ISSUE TITLE
immunization parsing

### ISSUE THREAD

**Issue by sayan801** [sayan801/pyccda#6]
# ../testdata/26775_ClinicalVisitSummary_CCDA.xml 

````
======================================================================
ERROR: test_sample_ccda_files (__main__.CcdaDocumentTestCase)
Test all sample CCDA files in the testdata directory.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ccda_test.py", line 35, in test_sample_ccda_files
    self._test_to_message(fp)
  File "ccda_test.py", line 22, in _test_to_message
    ccda_message = ccda_doc.to_message()
  File "/home/chandra/code/pyccda/pyccda/ccda.py", line 259, in to_message
    Root.IMMUNIZATION_PRODUCT, parent=entry)[0]
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 4.975s

````

**Comment by soumik-technicise** [comment]
# sample xml for immunization multiple value

[InPatient_v2.xml.zip](https://github.com/sayan801/pyccda/files/902911/InPatient_v2.xml.zip)
[InPatient_v2-1.xml.zip](https://github.com/sayan801/pyccda/files/902913/InPatient_v2-1.xml.zip)

[26789_ExportSummary_CCDA.xml.zip](https://github.com/sayan801/pyccda/files/902915/26789_ExportSummary_CCDA.xml.zip)

[26933_ExportSummary_CCDA.xml.zip](https://github.com/sayan801/pyccda/files/902916/26933_ExportSummary_CCDA.xml.zip)

[Ambulatory_v2.xml.zip](https://github.com/sayan801/pyccda/files/902917/Ambulatory_v2.xml.zip)
[Ambulatory_v2-1.xml.zip](https://github.com/sayan801/pyccda/files/902918/Ambulatory_v2-1.xml.zip)
